### ISSUE TITLE
svg exporting with cropped dimensions

### ISSUE THREAD

**Issue by Deep-Codes** [yWorks/svg2pdf.js#179]
My SVG exports in a cropped way in the PDF

Here's the svg

[map.txt](https://github.com/yWorks/svg2pdf.js/files/6572877/map.txt)

Svg is rendered correctly as this:

<img width="1326" alt="Screenshot 2021-06-01 at 7 32 37 AM" src="https://user-images.githubusercontent.com/61158210/120256350-8c103280-c2ab-11eb-98b8-c26459851950.png">

But on export looks like this: 

<img width="620" alt="Screenshot 2021-06-01 at 7 33 13 AM" src="https://user-images.githubusercontent.com/61158210/120256390-a1855c80-c2ab-11eb-840a-b0447b3b2b73.png">

**Comment by HackbrettXXX** [comment]
Thanks for reporting this bug. It seems like svg2pdf applies the clip path established by the inner `<svg>` element wrong. I suspect that the fallback value if no width/height is specified might be wrong here, although I might be wrong:

https://github.com/yWorks/svg2pdf.js/blob/74679131f6045bda56f7ef21640d7c26c4576f18/src/nodes/svg.ts#L122-L125

What happens is: the outer `<svg>` element establishes a clip rect 600x600 and a viewport transformation because of it's `viewBox` attribute. The inner `<svg>` adds another clip rect 600x600. However, this is applied in the scaled coordinate system established by the outer `<svg>`.

A workaround would probably be to remove the inner `<svg>` element or replace it by a `<g>` element.

**Comment by Deep-Codes** [comment]
@HackbrettXXX Thanks for an extremely fast response

You're Correct replacing it with the `<g>` tag works.

<img width="616" alt="Screenshot 2021-06-01 at 4 33 38 PM" src="https://user-images.githubusercontent.com/61158210/120313042-2053b700-c2f7-11eb-924a-58ef566c84fd.png">

I am gonna remove the nested `<svg>` tag from the Layout seems redundant.

So now I can add `export to pdf` feature in https://www.chloromaps.com/

Would acknowledge this library in the `/acknowledgment` section.

Thanks a Ton Again! 🎉

**Comment by Deep-Codes** [comment]
@HackbrettXXX 

Here's codesandbox Reprod in react https://codesandbox.io/s/silent-cache-vsldd?file=/src/App.js

If you copy the SVG on paste it in Playground it would correctly give output.

but here it's cropped

**Comment by yGuy** [comment]
Please strip down the SVG to a small repro and try debugging/bisecting your app against our playground. Please understand that we are only willing to debug large custom code bases in extreme cases - and we're certainly not there. 
It's great if you report a bug, but please report it properly and don't just drop a complete application for others to debug.
Thanks.

**Comment by Deep-Codes** [comment]
> Please strip down the SVG to a small repro and try debugging/bisecting your app against our playground. Please understand that we are only willing to debug large custom code bases in extreme cases - and we're certainly not there.
> It's great if you report a bug, but please report it properly and don't just drop a complete application for others to debug.
> Thanks.

Understandable, closing this Thanks ✅

**Comment by zornwal** [comment]
I have the same issue, and it is not caused by having a nested SVG element. I use [this example](http://raw.githack.com/yWorks/svg2pdf.js/master/?svg=%253Csvg%2520version%253D%25221.1%2522%2520height%253D%2522198%2522%2520width%253D%2522198%2522%2520xmlns%253D%2522http%253A%252F%252Fwww.w3.org%252F2000%252Fsvg%2522%253E%250A%2520%2520%253Cpath%2520id%253D%2522chart_57723_1_Series_0%2522%2520opacity%253D%25221%2522%2520fill%253D%2522none%2522%2520stroke%253D%2522%252300bdae%2522%2520stroke-width%253D%25222%2522%2520stroke-dasharray%253D%25220%2522%2520d%253D%2522M%25200%252050%2520L%252050%252025%2520L%2520100%252050%2522%2520clip-path%253D%2522none%2522%2520style%253D%2522visibility%253A%2520visible%253B%2522%253E%253C%252Fpath%253E%250A%253C%252Fsvg%253E%250A) which renders correctly in the playground, but when I try to add it to a pdf with height and width like so
```
let doc = new jsPDF('p','px','a4');
doc.svg(
    item.chart.svgObject, 
    { x: item.layout.pos.x, y: item.layout.pos.y, width: 50, height: 75 })
.then(() => doc.save("hat.pdf"));
```
it results in the generated pdf being clipped, rather than scaled to size, as seen below.
![image](https://user-images.githubusercontent.com/22613687/127141573-72e8f7cb-4d8b-4958-971b-65469205672a.png)

As deep code mentions, the svg is rendered perfectly fine in the playground and in my own html, but when added and saved programmatically, it clips the svg instead of scaling it.

I can open a separate issue this if you want it.

**Comment by HackbrettXXX** [comment]
@zornwal the issue can probably be resolved by specifying a `viewBox` attribute on the SVG.

The current behavior of svg2pdf is, that, if the `width` and `height` options are specified, they override the `width` and `height attributes on the SVG element. This means if no `viewBox` attribute is specified, the SVG won't be scaled.

**Comment by zornwal** [comment]
@HackbrettXXX So I should add a `viewBox` for the containing SVG then? If I want size (and scale) to be governed by the parameters given with `doc.svg(...)` what parameters should I give the `ViewBox` attribute?
