### ISSUE TITLE
SVG arcs don't work in Safari and Firefox

### ISSUE THREAD

**Issue by TorsteinHonsi** [yWorks/svg2pdf.js#22]
After fixing #10, arcs display fine in Chrome, but Safari and Firefox simply leave them out. It can be seen with test no 21 in the repo:

![skjermbilde 2017-03-21 kl 11 32 46](https://cloud.githubusercontent.com/assets/227836/24143535/4d678248-0e2a-11e7-8765-fbcc8eb65501.png)

**Comment by yGuy** [comment]
True - the reason is that the new code only runs when there is no "pathSegList" JS property, which still exists for Firefox and Safari, but is gone with Chrome. We should probably just move the 
`SvgPath && (d = SvgPath(d).unshort().unarc().abs().toString());` part higher up in front of the return statement in getPathSegList() since the calling code expects all of the svg path oddities to have already been removed when the call returns.

**Comment by TorsteinHonsi** [comment]
Thanks! I would like to try this and send a PR. In the mean time, can you tell me, or document in readme.md how the workflow is at the moment? The test files refer to `svg2pdf.min.js`, which is concatenated from source files and minified using Uglify and apparently there is a plugin to preserve the license headers. What commands do I run to build it?

**Comment by yGuy** [comment]
Actually building should be simple: there are [scripts defined in package.json](https://github.com/yWorks/svg2pdf.js/blob/master/package.json#L12) so you can do 
    
    npm run build 

and it should build the minified sources along with source maps so that you can conveniently run and debug the tests.

**Comment by TorsteinHonsi** [comment]
Ah, thanks!

**Comment by TorsteinHonsi** [comment]
Moving the path definition line up in front of the return statement didn't cut it. However, completely removing the return statement works for both Firefox and Safari. Is that a viable solution, or are you aware of any horrible side effects?

**Comment by yGuy** [comment]
You need of course set the "d" attribute anew after cleaning up the string. Just moving the line alone will not work. This however modifies the SVG and as such is not a nice solution, anyway. 

I guess simply always using the Chrome code (removing the `if`) should work well. Otherwise we would have the same horrible side-effects in Chrome. I am not aware of any such side-effects, other than possibly a loss in performance.

**Comment by TorsteinHonsi** [comment]
Probably the cleanest solution would be to mimic the arc segment in the segment list, and to the transform to a curve [here instead](https://github.com/yWorks/svg2pdf.js/blob/master/src/svg2pdf.js#L474). But your proposed fix works, hence the PR. Would appreciate a pull and a version bump.

**Comment by yGuy** [comment]
Sorry, but as I said before, I don't like the way we are now modifying the document. I would rather just get rid of the FF/Safari branch and always go with the Chrome branch.
