### ISSUE TITLE
stroke-width="inherit" breaks in jsPDF

### ISSUE THREAD

**Issue by KacperMadej** [yWorks/svg2pdf.js#227]
**Describe the bug**
An error is thrown `Error: Invalid argument passed to jsPDF.scale` when `stroke-width="inherit"` is used.

**To Reproduce**
See this [playground](http://raw.githack.com/yWorks/svg2pdf.js/master/index.html?svg=%253Csvg%2520viewBox%253D%25220%25200%2520100%2520100%2522%2520height%253D%2522100%2522%2520width%253D%2522100%2522%2520xmlns%253D%2522http%253A%252F%252Fwww.w3.org%252F2000%252Fsvg%2522%2520version%253D%25221.1%2522%253E%250A%2520%2520%253Cg%2520stroke-width%253D%25223%2522%253E%250A%2520%2520%2520%2520%253Cpath%2520stroke-width%253D%2522inherit%2522%2520stroke%253D%2522red%2522%2520d%253D%2522M%252020%252020%2520L%252050%252050%2520L%252020%252050%2520Z%2522%2520fill%253D%2522yellow%2522%253E%253C%252Fpath%253E%250A%2520%2520%253C%252Fg%253E%250A%253C%252Fsvg%253E).

**Expected behavior**
I would have expected the PDF to look like so. 
![image](https://user-images.githubusercontent.com/8960408/190376279-6ea72484-2d60-4b11-b7b6-bcaff5b89c6e.png)

```svg
<svg version="1.1" xmlns="http://www.w3.org/2000/svg" width="100" height="100" viewBox="0 0 100 100">
  <g stroke-width="3">
    <path fill="yellow" d="M 20 20 L 50 50 L 20 50 Z" stroke="red" stroke-width="inherit"></path>
  </g>
</svg>
```

**Desktop:**
 - OS: Windows 11
 - Browser: Chrome ()
 - Chrome Version 104.0.5112.102 (Official Build) (64-bit)

**Additional context**
It might be a purely jsPDF bug but I am not able to recreate a simple demo to report the problem there - if this is the case and you could help with passing the bug report to the correct place I will be grateful.

**Comment by yGuy** [comment]
Thanks for the report and repro. I am not 100% sure whether `inherit` is actually a valid value, here? This is not CSS but a presentation attribute and the way I read the spec I don't think you can have it here. At least you don't *need* it because if you simply omit it, it results in the behavior that you are looking for and the value will be inherited from the `g` element. And this actually [works with the PDF export](http://raw.githack.com/yWorks/svg2pdf.js/master/index.html?svg=%253Csvg%2520version%253D%25221.1%2522%2520xmlns%253D%2522http%253A%252F%252Fwww.w3.org%252F2000%252Fsvg%2522%2520width%253D%2522100%2522%2520height%253D%2522100%2522%2520viewBox%253D%25220%25200%2520100%2520100%2522%253E%250A%2520%2520%253Cg%2520stroke-width%253D%25223%2522%253E%250A%2520%2520%2520%2520%253Cpath%2520fill%253D%2522yellow%2522%2520d%253D%2522M%252020%252020%2520L%252050%252050%2520L%252020%252050%2520Z%2522%2520stroke%253D%2522red%2522%253E%253C%252Fpath%253E%250A%2520%2520%253C%252Fg%253E%250A%253C%252Fsvg%253E), too

**Comment by KacperMadej** [comment]
Thank you for the fast reply. I am not able to find the proper SVG spec for that so this is probably not valid and, as you pointed out, not really needed. I think it is safe to close the issue.
