### ISSUE TITLE
SVG is not properly rendered in the pdf

### ISSUE THREAD

**Issue by robiXxu** [yWorks/svg2pdf.js#228]
**Describe the bug**
I have a chartWindRose on a page. 
(I'm using angular components to create this svg)

![chartWindRose-expected](https://user-images.githubusercontent.com/1962141/191444894-170b22fb-2e12-4a16-b1e2-97acfa1fffc3.png)
( https://codepen.io/robixxu/pen/mdLMbgY )

This is what i get in the pdf

![chartWindRose-pdf](https://user-images.githubusercontent.com/1962141/191442309-79fac1b3-52e8-48a5-8414-3600065140e1.png)

I tried to debug it myself (cloned the lib & npm link in my project but i see no logs - not sure what is going on)

What version are you using (exact version of svg2pdf.js and jspdf)?
```
"jspdf": "^2.5.1",
"svg2pdf.js": "^2.2.1",
```

**To Reproduce**
1. Copy source from https://codepen.io/robixxu/pen/mdLMbgY
2. Test it on [online playground](http://raw.githack.com/yWorks/svg2pdf.js/master/) (couldn't paste the direct url => 414 Request-URI Too Large)

**Expected behavior**
I should see the chart
![chartWindRose-expected](https://user-images.githubusercontent.com/1962141/191444651-95e06ec6-67a7-4458-997c-1e3b30b237fb.png)

**Desktop (please complete the following information):**
 - OS: macOS Monterey 12.6
 - Browser: Tested on 
   * Chrome - Version 105.0.5195.125 (Official Build) (x86_64)
   * Safari - Version 16.0 (17614.1.25.9.10, 17614)
   * Firefox - 105.0 (64-bit) <<< not rendering the chart (as expected) & pdf (at all)

**Comment by waruyama** [comment]
The issue is caused by the curly braces in the HTML comments. I think this is a valid bug, as everything between `<!--` and `-->` should just be ignored.

Also, note that in the codepen the same SVG is included twice, probably by accident.

**Comment by robiXxu** [comment]
> The issue is caused by the curly braces in the HTML comments. I think this is a valid bug, as everything between `<!--` and `-->` should just be ignored.

Removed all html comments https://codepen.io/robixxu/pen/MWGJmzq but i get the same result


> Also, note that in the codepen the same SVG is included twice, probably by accident.

Yes, fixed.

**Comment by yGuy** [comment]
The problem is something else. I don't believe the curly braces are a problem. At least they do work in my stripped down test:

[Playground Link](
http://raw.githack.com/yWorks/svg2pdf.js/master/index.html?svg=%253Csvg%2520viewBox%253D%2522-1.2%2520-1.2%25202.4%25202.4%2522%2520height%253D%2522100%2525%2522%2520width%253D%2522100%2525%2522%253E%250A%2520%2520%250A%2509%253Ctext%2520fill%253D%2522red%2522%2520style%253D%2522font-size%253A%25201.1%2525%253B%2522%2520transform%253D%2522translate%28-0.5%252C%2520-0.5%29%2522%253ET%253C%252Ftext%253E%250A%2509%253Ctext%2520fill%253D%2522green%2522%2520style%253D%2522font-size%253A%25200.1%2522%2520transform%253D%2522translate%28%252B0.5%252C%2520-0.5%29%2522%253ET%253C%252Ftext%253E%250A%2520%2520%2520%2520%253Cpath%2520d%253D%2522M%25200%25200%252CL%25200.1%25200.0%2520%25200.1%25200.1%2520z%2522%2520fill%253D%2522red%2522%2520stroke%253D%2522black%2522%2520stroke-width%253D%25220.01%2522%2520transform%253D%2522translate%28-0.5%252C%25200%29%2522%253E%253C%252Fpath%253E%250A%2520%2520%2520%2520%253Cpath%2520d%253D%2522M%25200%25200%2520L%25200.1%25200.0%2520%25200.1%25200.1%2520z%2522%2520fill%253D%2522green%2522%2520stroke%253D%2522black%2522%2520stroke-width%253D%25220.01%2522%2520transform%253D%2522translate%28%252B0.5%252C%25200%29%2522%253E%253C%252Fpath%253E%250A%253C%252Fsvg%253E)

The problems are: 
There is a bug in your SVG for the path syntax. It's invalid and it seems svg2pdf is less lenient than the browser, here:

You may not have a comma after the MoveTo command, so instead of `d="M 0 0,L 1 1"` you need to have `d="M 0 0 L 1 1"`. There is no comma allowed between the draw commands: [Spec](https://www.w3.org/TR/SVG/paths.html#PathDataBNF)

The other problem is that your font size is given in percentage units. Svg2pdf does not understand this (a percentage of what?). Change your SVG to use absolute font sizes and it will work as in my example.
