### ISSUE TITLE
fill-opacity is only applied to one element, subsequent elements ignored

### ISSUE THREAD

**Issue by TorsteinHonsi** [yWorks/svg2pdf.js#29]
Live demo: https://jsfiddle.net/7r9r26vL/4/

**Comment by yGuy** [comment]
This actually turns out to be a bug in our version of JSPDF: since the graphics state is deemed equal for the subsequent rect, we do not set the opacity state but rely on it still being the active state. However "restoreGraphicsState" does not reset the "activeGState" variable in "resotreGraphicsState" and is called after each primitive. Ideally we would also keep a stack for the graphics states, but as a short-term workaround setting the activeGState variable to null in restoreGraphicsState should fix the issue already.

**Comment by yGuy** [comment]
Closing as "duplicate" to https://github.com/yWorks/jsPDF/issues/5

**Comment by yGuy** [comment]
We need to update to 1.2.69 of jspdf for this fix.

**Comment by Vasilcenko** [comment]
Updated jsPDF to 1.2.69
